CREATE TABLE IF NOT EXISTS SCRIB(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MESSAGE TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_MESSAGE ON SCRIB(MESSAGE);
CREATE INDEX IDX_CREATED_AT ON SCRIB(CREATED_AT);
CREATE INDEX IDX_UP DATED_AT ON SCRIB(UPDATED_AT);