name: Slate Build
on: push

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: /app
    steps:
      - uses: actions/checkout@v1
      - uses: ./github-actions/stack-actions-test
