name: Slate Build
on: push

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set tag name
        if: startsWith(github.ref, 'refs/tags/')
        id: tag
        shell: bash
        run: |
          echo "ref : ${{ github.ref }}"
          echo ${{ github.ref }} | grep -oP '(?<=refs/tags/v).+(?=$)'

      # - id: haskell-action
      #   uses: haskell/actions/setup@v1.1.5
      #   with:
      #     ghc-version: '8.8.4'
      #     cabal-version: 'latest'
      #     enable-stack: true
      #     stack-version: 'latest'

      # - uses: actions/cache@v2.1.3
      #   name: Cache them builds
      #   with:
      #     path: /home/runner/.stack
      #     key: ${{ runner.os }}-ghc8.8.4-stack

      # - run: stack test

      # - id: slate-exe
      #   shell: bash
      #   run: echo "::set-output name=slate-exe::$(stack path --local-install-root)"

      # - name: Statsify
      #   shell: bash
      #   run: |
      #     echo "executable location: ${{ steps.slate-exe.outputs.slate-exe }}"
      #     echo "tag name: $GIT_TAG_NAME"
      #     echo "executable: $(ls -l  ${{ steps.slate-exe.outputs.slate-exe }}/bin/)"

      # - name: Prepare Artifact
      #   shell: bash
      #   id: prep-artifact
      #   run: |
      #     mkdir dist
      #     mv "${{ steps.slate-exe.outputs.slate-exe }}/bin/slate" "dist/slate-${{ steps.tag.outputs.tag }}-${{ runner.os }}"
      #     echo "::set-output name=artifact-name::$(ls dist/slate-*)"

      # - name: Statsify Artifact
      #   shell: bash
      #   run: |
      #     echo "ref : ${{ github.ref }}"
      #     echo "artifact name: ${{ steps.prep-artifact.outputs.artifact-name }}"

      # - uses: fnkr/github-action-ghr@v1.3
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     GHR_PATH: "${{ steps.prep-artifact.outputs.artifact-name }}"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}