name: Slate Build
on: push

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     stackage: ["LTS-16.26"]

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run stack test

      # - uses: actions/cache@v2.1.3
      #   name: Cache stack-cache
      #   with:
      #     path: /app/build/stack-root
      #     key: ${{ runner.os }}-${{ matrix.stack }}-${{ matrix.cabal }}-${{ matrix.ghc }}-stack

      # - name: Stack Exec
      #   run: |
      #     stack --allow-different-user --stack-root /app/build/stack-root install
