name: Slate Build
on: push

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     stackage: ["LTS-16.26"]

    steps:
      - uses: actions/checkout@v2

      - id: haskell-action
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v2.1.3
        name: Cache them builds
        with:
          path: /home/runner/.stack
          key: ${{ runner.os }}-ghc8.8.4-stack

      - run: stack test

      - id: slate-exe
        shell: bash
        run: echo "::set-output name=slate-exe::$(stack path --local-install-root)"

      - name: Dump exec1
        shell: bash
        run: |
          echo "Executable1: ${{ steps.slate-exe.outputs.slate-exe }}"
          ls -l  ${{ steps.slate-exe.outputs.slate-exe }}/bin/"

      # - uses: fnkr/github-action-ghr@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     GHR_PATH: ${{ steps.stack-test.outputs.stack-exe  }}
      #     GITHUB_TOKEN: ${{ secrets.GHR_TOKEN }}
