name: Slate Build
on: push

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     stackage: ["LTS-16.26"]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v2.1.3
        name: Cache them builds
        with:
          path: /home/runner/.stack
          key: ${{ runner.os }}-ghc8.8.4-stack

      - id: stack-test
        run: stack test

      - name: Dump exec1
        run: echo "Executable1: ${{ steps.stack-test.outputs.stack-exe }} "

      - name: stack install
        run: stack install

      - name: Dump exec1
        run: echo "Executable2: ${{ steps.stack-test.outputs.stack-exe }} "

      # - uses: fnkr/github-action-ghr@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   env:
      #     GHR_PATH: ${{ steps.stack-test.outputs.stack-exe  }}
      #     GITHUB_TOKEN: ${{ secrets.GHR_TOKEN }}
