name: Slate Build
on:
  push:
    branch:
      - main

jobs:
  run-tests:
    name: Slate Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: haskell-action
        uses: haskell/actions/setup@v1.1.5
        with:
          ghc-version: '8.8.4'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v2.1.3
        name: Cache them builds
        with:
          path: /home/runner/.stack
          key: ${{ runner.os }}-ghc8.8.4-stack

      - run: stack test
